### ISSUE TITLE
Build issue with limits library

### ISSUE THREAD

**Issue by MarkMegarry** [wineslab/ns-o-ran-ns3-mmwave#10]
Hi all,

Following the instructions to set up ns-O-RAN from [Open RAN Gym](https://openrangym.com/tutorials/ns-o-ran), I ran into an issue building this project with GCC version 11.4.0.

After running `./waf build`, I encountered an error involving `src/core/helper/csv-reader.cc` which indicated that the `limits` library was not a part of `std`.

I was able to resolve this and build the project after adding the line `#include <limits>` to `src/core/helper/csv-reader.cc`, but I'm curious to find out if this problem was unique to my setup, or if it's a problem related to recent versions of GCC. Either way, I thought this was worth reporting.

This occured on Ubuntu 22.04.3 LTS.

**Comment by Devaansh-Kumar** [comment]
I faced the same issue, and adding `#include <limits>` fixed it.

**Comment by Thecave3** [comment]
Hi everyone, this is a known issue, please check #1

**Comment by amjed-altaweel** [comment]
Hello
im having few issues while building the ns3 using  "./ns3 build", alot of errors appears, and then the building process stops,  such as:

-------------------------------------------------------------
In file included from /usr/include/eigen3/Eigen/Core:199,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /home/amjed/ns-3-mmwave-oran/src/core/model/matrix-array.cc:23:
/usr/include/eigen3/Eigen/src/Core/arch/AVX/PacketMath.h: In function ‘Eigen::internal::Packet8bf Eigen::internal::F32ToBf16(const Packet8f&)’:
/usr/include/eigen3/Eigen/src/Core/arch/AVX/PacketMath.h:1275:13: warning: unused variable ‘r’ [-Wunused-variable]
 1275 |   Packet8bf r;
--------------------------------------------------------------
In file included from /usr/include/c++/13/algorithm:60,
                 from /home/amjed/ns-3-mmwave-oran/cmake-cache/CMakeFiles/stdlib_pch-optimized.dir/cmake_pch.hxx:5,
                 from <command-line>:
In static member function ‘static void std::__copy_move<false, false, std::random_access_iterator_tag>::__assign_one(_Tp*, _Up*) [with _Tp = int; _Up = int]’,
    inlined from ‘static _Up* std::__copy_move_backward<_IsMove, true, std::random_access_iterator_tag>::__copy_move_b(_Tp*, _Tp*, _Up*) [with _Tp = int; _Up = int; bool _IsMove = false]’ at /usr/include/c++/13/bits/stl_algobase.h:751:20,
    inlined from ‘_BI2 std::__copy_move_backward_a2(_BI1, _BI1, _BI2) [with bool _IsMove = false; _BI1 = int*; _BI2 = int*]’ at /usr/include/c++/13/bits/stl_algobase.h:769:37,
    inlined from ‘_BI2 std::__copy_move_backward_a1(_BI1, _BI1, _BI2) [with bool _IsMove = false; _BI1 = int*; _BI2 = int*]’ at /usr/include/c++/13/bits/stl_algobase.h:778:51,
    inlined from ‘_OI std::__copy_move_backward_a(_II, _II, _OI) [with bool _IsMove = false; _II = __gnu_cxx::__normal_iterator<int*, vector<int> >; _OI = __gnu_cxx::__normal_iterator<int*, vector<int> >]’ at /usr/include/c++/13/bits/stl_algobase.h:807:31,
    inlined from ‘_BI2 std::copy_backward(_BI1, _BI1, _BI2) [with _BI1 = __gnu_cxx::__normal_iterator<int*, vector<int> >; _BI2 = __gnu_cxx::__normal_iterator<int*, vector<int> >’ at /usr/include/c++/13/bits/stl_algobase.h:867:7,
    inlined from ‘void AttributeContainerObject::ReverseList()’ at /home/amjed/ns-3-mmwave-oran/src/core/test/attribute-container-test-suite.cc:148:23:
/usr/include/c++/13/bits/stl_algobase.h:398:17: warning: array subscript -1 is outside array bounds of ‘int [2305843009213693951]’ [-Warray-bounds=]
  398 |         { *__to = *__from; }
---------------------------------------------------------------
In file included from /home/amjed/ns-3-mmwave-oran/src/wifi/model/sta-wifi-mac.cc:22:
/home/amjed/ns-3-mmwave-oran/src/wifi/model/sta-wifi-mac.h:152:34: error: ‘uint8_t’ is not a member of ‘std’; did you mean ‘wint_t’?
  152 |         std::list<std::pair<std::uint8_t, uint8_t>> m_setupLinks;
      |                                  ^~~~~~~
      |                                  wint_t
/home/amjed/ns-3-mmwave-oran/src/wifi/model/sta-wifi-mac.h:152:43: error: template argument 1 is invalid
  152 |         std::list<std::pair<std::uint8_t, uint8_t>> m_setupLinks;
      |                                           ^~~~~~~
/home/amjed/ns-3-mmwave-oran/src/wifi/model/sta-wifi-mac.h:152:50: error: template argument 1 is invalid
  152 |         std::list<std::pair<std::uint8_t, uint8_t>> m_setupLinks;
      |                                                  ^~
/home/amjed/ns-3-mmwave-oran/src/wifi/model/sta-wifi-mac.h:152:50: error: template argument 2 is invalid
[ 50%] Building CXX object src/internet/CMakeFiles/libinternet-obj.dir/model/tcp-westwood-plus.cc.o
[ 50%] Building CXX object src/internet/CMakeFiles/libinternet-obj.dir/model/tcp-yeah.cc.o
/home/amjed/ns-3-mmwave-oran/src/wifi/model/sta-wifi-mac.cc: In member function ‘void ns3::StaWifiMac::ScanningTimeout(const std::optional<ApInfo>&)’:
/home/amjed/ns-3-mmwave-oran/src/wifi/model/sta-wifi-mac.cc:563:56: error: ‘begin’ was not declared in this scope; did you mean ‘std::begin’?
  563 |     for (const auto& [localLinkId, apLinkId] : bestAp->m_setupLinks)
      |                                                        ^~~~~~~~~~~~
      |                                                        std::begin
In file included from /usr/include/c++/13/string:53,
                 from /usr/include/c++/13/bits/locale_classes.h:40,
                 from /usr/include/c++/13/bits/ios_base.h:41,
                 from /usr/include/c++/13/ios:44,
                 from /usr/include/c++/13/istream:40,
                 from /usr/include/c++/13/fstream:40,
                 from /home/amjed/ns-3-mmwave-oran/cmake-cache/CMakeFiles/stdlib_pch-optimized.dir/cmake_pch.hxx:9,
                 from <command-line>:
/usr/include/c++/13/bits/range_access.h:114:37: note: ‘std::begin’ declared here
  114 |   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&) noexcept;
      |                                     ^~~~~
/home/amjed/ns-3-mmwave-oran/src/wifi/model/sta-wifi-mac.cc:563:56: error: ‘end’ was not declared in this scope; did you mean ‘std::end’?
  563 |     for (const auto& [localLinkId, apLinkId] : bestAp->m_setupLinks)
      |                                                        ^~~~~~~~~~~~
      |                                                        std::end
/usr/include/c++/13/bits/range_access.h:116:37: note: ‘std::end’ declared here
  116 |   template<typename _Tp> const _Tp* end(const valarray<_Tp>&) noexcept;
-----------------------------------------------------------------------
gmake[2]: *** [src/wifi/CMakeFiles/libwifi-obj.dir/build.make:1598: src/wifi/CMakeFiles/libwifi-obj.dir/model/sta-wifi-mac.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:14088: src/wifi/CMakeFiles/libwifi-obj.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
---------------------------------------------------------------------------
In file included from /home/amjed/ns-3-mmwave-oran/build/optimized/include/ns3/epc-x2-sap.h:1,
                 from /home/amjed/ns-3-mmwave-oran/src/lte/model/epc-x2.h:29,
                 from /home/amjed/ns-3-mmwave-oran/build/optimized/include/ns3/epc-x2.h:1,
                 from /home/amjed/ns-3-mmwave-oran/src/lte/model/epc-x2.cc:25:
In copy constructor ‘ns3::EpcX2Sap::LoadInformationParams::LoadInformationParams(const ns3::EpcX2Sap::LoadInformationParams&)’,
    inlined from ‘void ns3::EpcX2::RecvFromX2cSocket(ns3::Ptr<ns3::Socket>)’ at /home/amjed/ns-3-mmwave-oran/src/lte/model/epc-x2.cc:385:45:
/home/amjed/ns-3-mmwave-oran/src/lte/model/epc-x2-sap.h:333:12: warning: ‘params.ns3::EpcX2Sap::LoadInformationParams::targetCellId’ may be used uninitialized [-Wmaybe-uninitialized]
  333 |     struct LoadInformationParams
      |            ^~~~~~~~~~~~~~~~~~~~~
/home/amjed/ns-3-mmwave-oran/src/lte/model/epc-x2.cc: In member function ‘void ns3::EpcX2::RecvFromX2cSocket(ns3::Ptr<ns3::Socket>)’:
/home/amjed/ns-3-mmwave-oran/src/lte/model/epc-x2.cc:380:49: note: ‘params’ declared here
  380 |             EpcX2SapUser::LoadInformationParams params;
      |                                                 ^~~~~~

--------------------------------------------------------------------------------------------------
