### ISSUE TITLE
[SCTP] recv: Connection reset by peer

### ISSUE THREAD

**Issue by lightxy233** [wineslab/ns-o-ran-ns3-mmwave#6]
Hi, I have built a relatively large-scale simulation program, in which the time interval between reporting messages to near-rt RIC in the real world may exceed 2 minutes. 

I found that when the simulation scale was relatively small(time interval is less than 1 minute), everything was okay. 

But if the scale is larger, there will be an error message in the terminal of ns3 when sending RIC Indication Message:

```
[INFO ] Send data to client_fd 9
[ERROR] [SCTP] recv: Connection reset by peer
[ERROR] [SCTP] Connection closed by remote peer
[ERROR] [SCTP] Connection closed by remote peer
[ERROR] [SCTP] Connection closed by remote peer
```

I think it means that E2Termination closed or reset the connection when time interval was too long, but i'm not sure. 

Has anyone encountered a similar problem?

**Comment by Thecave3** [comment]
Hello, can you provide more details regarding what are you trying to achieve?

Best

**Comment by lightxy233** [comment]
I apologize for my carelessness, `[SCTP] recv: Connection reset by peer` makes me hastily believe that there is a timeout issue.

I found that the reason for the error is that the RIC-INDICATION_MESSAGE sent was too large(over 2500 bytes) when there was a lot of UE information to be reported. After reducing the size of the message, container `e2term`  and ns-3 worked properly. 

So there's no such thing as a timeout issue, I will close this issue.

Thanks for your help.
